export enum RoleType {
  ADMIN = 'ADMIN',
  REFEREE_MANAGER = 'REFEREE_MANAGER',
  COMPETITION_MANAGER = 'COMPETITION_MANAGER',
  FINANCE_EMPLOYEE = 'FINANCE_EMPLOYEE',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
}
